import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Lato,
  Playfair_Display,
  Prata,
} from "next/font/google";
import "./globals.css";
const prata = Prata({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-prata",
});
const lato = Lato({
  variable: "--font-lato",
  weight: ["400", "700"],
  subsets: ["latin"],
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  weight: ["400", "700"],
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${prata.variable} ${playfair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
